import { useCallback, useSyncExternalStore } from "react";

export type Lang = "zh" | "en";

const STORAGE_KEY = "cfsm-nier:lang";

const STRINGS = {
  zh: {

    "nav.status": "状态",
    "nav.view": "视图",
    "nav.colors": "配色",
    "common.back": "← 返回",
    "common.backHome": "← 返回首页",
    "common.loading": "加载中…",
    "common.refresh": "刷新",
    "common.retry": "重试",
    "common.nodata": "暂无节点数据",
    "ping.latency": "延迟",
    "ping.loss": "丢包",
    "card.down": "↓ 下行",
    "card.up": "↑ 上行",
    "card.traffic": "流量",
    "card.uptime": "运行",
    "card.expire": "到期",
    "card.free": "免费",
    "card.permanent": "永久",
    "card.remaining": "余 {n}",
    "common.close": "关闭",
    "common.confirm": "确认",
    "common.applied": "已应用",
    "common.notApplied": "尚未应用，点击确认后生效",
    "common.detail": "详情",
    "common.realtime": "实时",
    "common.noData": "无数据",
    "common.failed": "加载失败",
    "common.samples": "个采样",    "list.node": "节点",
    "list.os": "系统",
    "list.mem": "内存",
    "list.disk": "磁盘",
    "list.load": "负载",
    "list.live": "实时",
    "list.traffic": "流量",
    "list.net": "网络",
    "list.uptime": "运行",
    "list.pingLines": "延迟线路",
    "list.online": "在线",
    "list.offline": "离线",
    "list.unknown": "状态未知",
    "list.resetStyle": "重置样式",
    "list.restoreCols": "恢复默认列宽与列设置",
    "list.dragHint": "拖拽调整",
    "card.mem": "内存",
    "card.disk": "磁盘",
    "card.swap": "Swap",
    "card.load": "负载",
    "card.conns": "连接数",
    "card.liveRate": "实时速率",
    "card.liveUp": "实时上行",
    "card.liveDown": "实时下行",
    "card.cumUp": "累计上行",
    "card.cumDown": "累计下行",
    "card.totalTraffic": "累计流量",
    "card.viewDetail": "查看详情",
    "card.switchLine": "切换线路",
    "card.restoreLine": "这台节点的线路恢复成站点设置",
    "card.lines": "各线路延迟与丢包",
    "card.noValidPing": "暂无有效 Ping 样本",
    "card.noSamples": "无样本",
    "card.homePing.loading": "正在加载首页 Ping",
    "card.homePing.fail": "首页 Ping 加载失败",
    "card.homePing.refreshFail": "首页 Ping 刷新失败，显示上次数据",
    "card.homePing.refreshing": "首页 Ping 正在刷新，显示上次数据",
    "card.homePing.unconfigured": "未配置首页 Ping",
    "home.filterRegion": "地区筛选",
    "home.siteName": "站点名称",
    "home.groups": "节点分组",
    "home.overviewTitle": "节点概览",
    "home.overview": "首页总览",
    "home.gridColumns": "卡片布局",
    "sort.mode": "排序方式",
    "sort.ascText": "升序",
    "sort.descText": "降序",
    "range.h1": "1 小时",
    "range.h2": "2 小时",
    "range.h3": "3 小时",
    "range.h7": "7 小时",
    "range.d1": "1 天",
    "range.d3": "3 天",
    "range.d7": "7 天",
    "range.d14": "14 天",
    "traffic.range": "时间范围",
    "traffic.refetch": "重新拉取该时间范围",
    "traffic.nodeChartTitle": "节点当日流量与网速",
    "instance.switch": "切换服务器",
    "instance.servers": "服务器",
    "instance.online": "在线",
    "instance.offline": "离线",
    "instance.unknown": "状态未知",
    "chart.swapNone": "Swap 无",
    "chart.up": "上行",
    "chart.down": "下行",
    "chart.usage": "使用率",
    "chart.write": "写入",
    "chart.read": "读取",
    "chart.range": "图表数据范围",
    "chart.usedSpace": "已用空间",
    "chart.diskIO": "磁盘 IO",
    "chart.net": "网络",
    "chart.proc": "进程",
    "chart.conn": "连接",
    "chart.avg": "均值",    "chart.series.ram": "内存",

    "chart.series.swap": "Swap",
    "chart.series.disk": "磁盘",
    "chart.series.read": "读取",
    "chart.series.write": "写入",
    "chart.series.in": "下行",
    "chart.series.out": "上行",
    "chart.series.proc": "进程",
    "chart.series.tcp": "TCP",
    "chart.series.udp": "UDP",
    "chart.days": "天",
    "chart.hours": "小时",
    "chart.minutes": "分钟",
    "chart.coverageFull": "覆盖完整",
    "chart.coverageActual": "实际覆盖",
    "chart.sampleEvery": "每 {text} 一个采样点",
    "chart.usedPrefix": "已用",
    "chart.readShort": "读",
    "chart.writeShort": "写",
    "chart.loadAt": "负载",
    "chart.interval": "间隔",
    "chart.task": "任务",
    "chart.failShort": "失败",

    "chart.jitter": "抖动",
    "chart.spanTooltip": "关闭：如实显示中断/丢包断点；开启：跨过所有空缺连成完整曲线。",
    "chart.lossTooltip": "在图表上方按线路显示丢包率色带：越红丢得越多，空缺表示该时段没有采样。查询超过 1 小时时，后端按采样点数返回，区间越长采样越粗。",
    "chart.smoothTooltip": "对尖峰值做轻度平滑，仅影响图线显示",
    "ping.noData": "无数据",
    "shell.viewSwitch": "切换卡片视图",
    "shell.appearance": "外观选择",
    "shell.adminLogin": "后台登录",
    "shell.adminPanel": "管理后台",
    "shell.refreshWarn": "30 分钟内已经刷新过；确实要再拉一次就再点一下",
    "shell.refreshFail": "刷新失败，点击重试",
    "shell.mobileNav": "移动端导航",
    "lang.zh": "中文",
    "lang.en": "English",
    "colors.keepBlue": "保留少量蓝灰层次",
    "colors.custom": "配色自定义",
    "colors.dragPick": "拖动取色",
    "colors.darkBg": "暗色背景",
    "colors.resetAll": "全部重置",
    "colors.darkHint": "切换到深色模式后查看实际效果",
    "colors.colorFor": "{label} 颜色",
    "colors.restoreFor": "恢复 {label} 默认色",
    "colors.pickFor": "{label} 颜色选择",
    "colors.hexFor": "{label} 十六进制颜色",
    "colors.current": "当前默认色",
    "colors.restore": "恢复默认",
    "colors.saveSiteHint": "把当前配色（连同其它本机设置）写到后端，成为所有设备与访客的默认值",
    "colors.depth": "暗色深度预设",
    "colors.deep": "深黑",
    "colors.grayBlack": "灰黑",
    "colors.pure": "纯黑",
    "colors.pureDesc": "纯黑画布，卡片保留层级",
    "colors.pick": "选择颜色",
    "colors.blackness": "黑色程度",
    "turnstile.scriptFail": "Turnstile 脚本加载失败",
    "turnstile.verifyFail": "验证失败",
    "turnstile.componentFail": "验证组件加载失败",
    "error.routeTitle": "路由错误",
    "error.renderFail": "页面渲染时发生异常",
    "spinner.loading": "加载中",
    "detail.mem": "内存",
    "detail.disk": "磁盘",

    "common.cores": "核",
    "common.unconfigured": "未配置",
    "overview.online": "在线节点",
    "overview.bandwidth": "实时带宽",
    "overview.traffic": "累计流量",
    "overview.all": "全部",
    "overview.empty.title": "尚未连接到任何节点",
    "overview.empty.sub": "等待后端推送或前往管理后台添加",
    "overview.loadfail.title": "节点数据暂时无法加载",
    "overview.loadfail.sub": "正在等待后端自动重试",
    "traffic.date": "日期",
    "traffic.today": "当日流量",
    "traffic.peak": "当日采样峰值",
    "traffic.nodes": "节点明细",
    "traffic.peakNote": "峰值按历史采样计算",
    "traffic.statTo": "统计至",
    "traffic.chartTitle": "节点流量与网速",
    "traffic.startDate": "起始日期",
    "traffic.waiting": "等待采样数据",
    "traffic.estimate": "左轴累计按采样积分估算",
    "traffic.emptyRange": "该时间范围内暂无采样数据",
    "traffic.needLogin": "查看超过 1 天的历史需要登录",
    "traffic.retention": "仅保留最近 14 天，图中为保留期内的数据",
    "traffic.chartFail": "节点图加载失败",
    "traffic.cumUp": "累计上行",
    "traffic.cumDown": "累计下行",
    "traffic.rateUp": "上行速率",
    "traffic.rateDown": "下行速率",
    "traffic.columnNode": "节点",
    "traffic.columnTotal": "当日流量",
    "traffic.columnPeakUp": "上行峰值",
    "traffic.columnPeakDown": "下行峰值",
    "traffic.columnAction": "操作",
    "traffic.columnLive": "实时",
    "traffic.up": "上行",
    "traffic.down": "下行",
    "traffic.noPeak": "暂无峰值",
    "detail.region": "地区",
    "detail.group": "分组",
    "detail.os": "系统",
    "detail.kernel": "内核",
    "detail.cpu": "CPU",
    "detail.arch": "架构",
    "detail.gpu": "GPU",
    "detail.stack": "IPv4 / IPv6",
    "detail.agent": "Agent",
    "detail.uptime": "运行时间",
    "detail.load": "负载",
    "detail.conns": "连接数",
    "detail.proc": "进程",
    "detail.notFound": "找不到这个实例，它可能已被删除或链接无效。",
    "detail.listFail": "节点列表加载失败，系统正在自动重试。",
    "detail.loading": "正在加载实例…",
    "chart.loadTitle": "负载图表",
    "chart.pingTitle": "Ping 图表",
    "chart.spanGaps": "断点连线",
    "chart.loadFail": "负载历史加载失败",
    "chart.loadEmpty": "暂无负载历史数据",
    "chart.pingFail": "延迟历史加载失败",
    "chart.pingEmpty": "暂无延迟记录",
    "chart.retrying": "重试中",
    "chart.refreshing": "刷新中",
    "chart.refreshFail": "刷新失败，重试",
    "chart.hideAll": "隐藏全部",
    "chart.showAll": "显示全部",
    "chart.lossBand": "丢包色带",
    "chart.smooth": "削峰平滑",
    "chart.allHidden": "当前已隐藏全部线路，点击上方按钮可恢复显示",
    "chart.coverage": "覆盖",
    "chart.sampling": "采样",
    "settings.defaultAppearance": "默认外观",
    "settings.cardView": "卡片视图",
    "settings.homeSort": "首页排序",
    "settings.defaultSort": "默认排序",
    "settings.defaultDir": "默认方向",
    "settings.cardLayout": "卡片布局",
    "settings.auto": "自动",
    "settings.cols": "列",
    "settings.groupOrder": "分组顺序（拖动排序）",
    "settings.noGroups": "节点还没有配置分组。",
    "settings.homeShow": "首页显示",
    "settings.showOverview": "显示总览",    "traffic.time": "时间",
    "traffic.chartAria": "节点当日流量累计与网速双轴图",
    "range.h6": "6 小时",
    "range.h12": "12 小时",
    "range.d2": "2 天",
    "settings.showOverviewDesc": "在线/离线/总带宽汇总面板",
    "settings.showGroupTabsDesc": "按节点分组切换",
    "settings.showRegionBarDesc": "按地区聚合",
    "settings.compactTraffic": "小卡显示累计流量",
    "settings.compactUptime": "小卡显示在线时长",
    "settings.showConnectionsDesc": "TCP/UDP（需探针上报）",
    "settings.multiPingDesc": "大/小卡片显示多条线路对比；关闭后单线路",
    "settings.fakePingDesc": "访客看到的模拟延迟由站长显式开启",
    "settings.adminBtnDesc": "顶栏 ADMIN 按钮",
    "settings.cardLayoutHint": "「自动」按卡片最小宽度自适配列数；选固定列数后，首页大/小/迷你卡片都按该列数排列。",
    "settings.cardViewHint": "桌面端与移动端共用同一视图；移动端选到 LIST 时自动回退为小卡片。",
    "manage.currentUsing": "当前设备正在使用：",
    "manage.saveLocalHint": "点上方「保存到本机」后新外观才写入本机偏好",
    "manage.resetHint": "撤销未保存的改动",
    "manage.restoreSiteHint": "丢弃本机设置，改用后端配置",
    "manage.copyJsonHint": "导出完整配置 JSON，粘到后台主题自定义配置",
    "manage.saveSiteHint": "直接写到后端 theme_options，所有访客生效",

    "settings.showGroupTabs": "显示分组页签",
    "settings.showRegionBar": "显示地区统计",
    "settings.showCardGroup": "卡片显示分组",
    "settings.compactList": "小卡片与列表",
    "settings.showConnections": "显示连接数",
    "settings.listCols": "表格列（LIST 视图）",
    "settings.pingLines": "延迟线路",
    "settings.multiPing": "多线路模式",
    "settings.fakePing": "未绑定节点模拟数据",
    "settings.defaultLine": "默认线路",
    "settings.other": "其他",
    "settings.adminBtn": "显示管理后台入口",
    "settings.pingChart": "详情页显示 Ping 图表",
    "settings.hiddenNodes": "隐藏节点（每行一个名称或 UUID）",
    "settings.surface": "卡片不透明度",
    "appearance.light": "浅色",
    "appearance.system": "跟随系统",
    "appearance.dark": "深色",
    "view.large": "大卡片",
    "view.compact": "小卡片",
    "view.mini": "迷你卡片",
    "view.list": "列表",
    "view.desktop": "桌面",
    "view.mobile": "移动端",
    "sort.asc": "↑ 升序",
    "sort.desc": "↓ 降序",
    "sort.default": "默认",
    "sort.name": "名称",
    "sort.speed": "实时网速",
    "sort.traffic": "累计流量",
    "manage.reset": "重置",
    "manage.restoreSite": "改用后端配置",
    "manage.copyJson": "复制配置 JSON",
    "manage.saveLocal": "保存到本机",
    "manage.saveSite": "保存到后端",
    "manage.saving": "保存中…",
    "manage.publishing": "发布中…",
    "manage.saveLocalDone": "主题设置已保存到本机浏览器",
    "manage.saveSiteDone": "已保存到后端：所有设备与访客都会以这套配置为默认值",
    "manage.restoreDone": "已丢弃本机设置，改用后端当前的配置",
    "manage.copyDone": "配置 JSON 已复制，粘贴到后台「外观设置 → 主题自定义配置」保存即可成为所有设备的默认值",
    "manage.copyFail": "复制失败，请检查浏览器的剪贴板权限",
    "manage.loginExpired": "登录态已失效，请到 /admin 重新登录后再保存到后端（本机设置不受影响）",
    "manage.turnstile": "本站需要人机验证：完成弹出的验证后，再点一次「保存到后端」",
    "manage.invalidFormat": "配置格式被后端拒绝（invalidThemeOptionsFormat），请把这条信息反馈给作者",
    "manage.saveFail": "保存失败",
    "manage.siteHint": "登录站长可用「保存到后端」把当前配置直接写到站点 theme_options（所有访客生效）；未登录时用「复制配置 JSON」粘到后台「外观设置 → 主题自定义配置」。",
    "shell.accessError": "无法读取站点配置",
    "shell.accessErrorSub": "请检查网络后重试。",
    "shell.private": "访问受限",
    "shell.privateSub": "站点已设为私有，登录后即可查看节点数据。",
    "shell.gotoLogin": "前往登录",
    "shell.more": "更多",
    "shell.colors": "卡片配色",
    "shell.theme": "主题",
    "lang.switch": "切换语言",
    "shell.cardView": "卡片视图",
    "shell.refreshLoading": "正在拉取 {n} 台节点最近 1 小时的延迟历史…",
    "shell.refreshBase": "刷新延迟数据：拉取 {n} 台节点最近 1 小时的真实采样",
    "shell.lastRefresh": "上次刷新",
    "turnstile.title": "身份验证",
    "turnstile.desc": "本站开启了 Cloudflare Turnstile 验证，通过后即可查看节点数据。",
    "turnstile.fail": "验证未通过，请重试",
    "turnstile.widgetFail": "人机验证组件加载失败",
    "turnstile.expired": "验证已过期，请重新完成验证",
    "realtime.expired": "实时连接已达到时限并断开",
    "realtime.limit": "站点限制单次实时连接",
    "realtime.paused": "页面停在断开前的数据。",
    "realtime.continue": "继续接收",
    "error.title": "页面出错了",
    "error.hint": "可以刷新页面，或返回首页重新进入。",
    "error.diag": "诊断信息（反馈时请一并截图或复制）",
    "error.copy": "复制诊断信息",
    "error.reload": "[ 刷新 ]",
    "error.routeFail": "当前路由加载失败。",
    "notfound.title": "页面未找到",

    "nav.assets": "资产",
    "nav.traffic": "流量",
    "nav.settings": "设置",
    "nav.admin": "后台",
    "title.status": "系统状态",
    "title.traffic": "今日流量",
    "title.assets": "资产统计",
    "title.settings": "主题设置",
    "status.online": "ONLINE",
    "status.offline": "OFFLINE",
    "status.pending": "等待后端推送…",
    "footer.tagline": "End of transmission // Glory to mankind",
  },
  en: {
    "nav.status": "Status",
    "nav.view": "View",
    "nav.colors": "Colors",
    "common.back": "← Back",
    "common.backHome": "← Back to Home",
    "common.loading": "Loading…",
    "common.refresh": "Refresh",
    "common.retry": "Retry",
    "common.nodata": "No nodes yet",
    "ping.latency": "Latency",
    "ping.loss": "Loss",
    "card.down": "↓ Down",
    "card.up": "↑ Up",
    "card.traffic": "Traffic",
    "card.uptime": "Uptime",
    "card.expire": "Expiry",
    "card.free": "Free",
    "card.permanent": "Permanent",
    "card.remaining": "{n} left",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.applied": "Applied",
    "common.notApplied": "Not applied yet — click Confirm to take effect",
    "common.detail": "Detail",
    "common.realtime": "Live",
    "common.noData": "No data",
    "common.failed": "Load failed",
    "common.samples": "samples",
    "list.node": "Node",
    "list.os": "OS",
    "list.mem": "Memory",
    "list.disk": "Disk",
    "list.load": "Load",
    "list.live": "Live",
    "list.traffic": "Traffic",
    "list.net": "Network",
    "list.uptime": "Uptime",
    "list.pingLines": "Latency Lines",
    "list.online": "Online",
    "list.offline": "Offline",
    "list.unknown": "Unknown",
    "list.resetStyle": "Reset Style",
    "list.restoreCols": "Reset column widths & visibility",
    "list.dragHint": "Drag to resize",
    "card.mem": "Memory",
    "card.disk": "Disk",
    "card.swap": "Swap",
    "card.load": "Load",
    "card.conns": "Connections",
    "card.liveRate": "Live Rate",
    "card.liveUp": "Live Up",
    "card.liveDown": "Live Down",
    "card.cumUp": "Cum. Up",
    "card.cumDown": "Cum. Down",
    "card.totalTraffic": "Total Traffic",
    "card.viewDetail": "View Detail",
    "card.switchLine": "Switch Line",
    "card.restoreLine": "Restore this node's line to site default",
    "card.lines": "Per-Line Latency & Loss",
    "card.noValidPing": "No valid Ping samples",
    "card.noSamples": "No samples",
    "card.homePing.loading": "Loading home Ping",
    "card.homePing.fail": "Home Ping load failed",
    "card.homePing.refreshFail": "Home Ping refresh failed, showing last data",
    "card.homePing.refreshing": "Home Ping refreshing, showing last data",
    "card.homePing.unconfigured": "Home Ping not configured",
    "home.filterRegion": "Region Filter",
    "home.siteName": "Site Name",
    "home.groups": "Node Groups",
    "home.overviewTitle": "Node Overview",
    "home.overview": "Home Overview",
    "home.gridColumns": "Card Layout",
    "sort.mode": "Sort By",
    "sort.ascText": "Ascending",
    "sort.descText": "Descending",
    "range.h1": "1 Hour",
    "range.h2": "2 Hours",
    "range.h3": "3 Hours",
    "range.h7": "7 Hours",
    "range.d1": "1 Day",
    "range.d3": "3 Days",
    "range.d7": "7 Days",
    "range.d14": "14 Days",
    "traffic.range": "Time Range",
    "traffic.time": "Time",
    "traffic.refetch": "Refetch This Range",
    "traffic.nodeChartTitle": "Nodes' Daily Traffic & Speed",
    "instance.switch": "Switch Server",
    "instance.servers": "Servers",
    "instance.online": "Online",
    "instance.offline": "Offline",
    "instance.unknown": "Unknown",
    "chart.swapNone": "No Swap",
    "chart.up": "Up",
    "chart.down": "Down",
    "chart.usage": "Usage",
    "chart.write": "Write",
    "chart.read": "Read",
    "chart.range": "Chart Range",
    "chart.usedSpace": "Used Space",
    "chart.diskIO": "Disk IO",
    "chart.net": "Network",
    "chart.proc": "Processes",
    "chart.conn": "Conn",
    "chart.avg": "Avg",
    "chart.series.ram": "Memory",
    "chart.series.swap": "Swap",
    "chart.series.disk": "Disk",
    "chart.series.read": "Read",
    "chart.series.write": "Write",
    "chart.series.in": "Down",
    "chart.series.out": "Up",
    "chart.series.proc": "Processes",
    "chart.series.tcp": "TCP",
    "chart.series.udp": "UDP",
    "chart.days": "d",
    "chart.hours": "h",
    "chart.minutes": "min",
    "chart.coverageFull": "Full coverage",
    "chart.coverageActual": "Actual coverage",
    "chart.sampleEvery": "one sample per {text}",
    "chart.usedPrefix": "Used",
    "chart.readShort": "R",
    "chart.writeShort": "W",
    "chart.loadAt": "Load",
    "chart.interval": "Interval",
    "chart.task": "Task",
    "chart.failShort": "Failed",
    "chart.jitter": "Jitter",
    "chart.spanTooltip": "Off: show interruptions/loss gaps as-is; On: connect across all gaps into a full curve.",
    "chart.lossTooltip": "Per-line loss bands above the chart: redder = more loss, gaps = no samples in that period. Queries over 1 hour are downsampled by the backend.",
    "chart.smoothTooltip": "Lightly smooth spikes; affects only the line display",
    "ping.noData": "No data",
    "shell.viewSwitch": "Switch Card View",
    "shell.appearance": "Appearance",
    "shell.adminLogin": "Admin Login",
    "shell.adminPanel": "Admin Panel",
    "shell.refreshWarn": "Refreshed within the last 30 minutes; click again to force",
    "shell.refreshFail": "Refresh failed, click to retry",
    "shell.mobileNav": "Mobile Navigation",
    "lang.zh": "中文",
    "lang.en": "English",
    "colors.keepBlue": "Keep subtle blue-grey tones",
    "colors.custom": "Custom Palette",
    "colors.dragPick": "Drag to pick color",
    "colors.darkBg": "Dark Background",
    "colors.resetAll": "Reset All",
    "colors.darkHint": "Switch to dark mode to preview",
    "colors.colorFor": "{label} color",
    "colors.restoreFor": "Restore {label} default",
    "colors.pickFor": "Pick {label} color",
    "colors.hexFor": "{label} hex color",
    "colors.current": "Current Default",
    "colors.restore": "Restore Default",
    "colors.saveSiteHint": "Write the current palette (with other local settings) to the backend as the default for all devices and visitors",
    "colors.depth": "Dark Depth Presets",
    "colors.deep": "Deep Black",
    "colors.grayBlack": "Grey Black",
    "colors.pure": "Pure Black",
    "colors.pureDesc": "Pure black canvas, cards keep depth",
    "colors.pick": "Pick Color",
    "colors.blackness": "Blackness",
    "turnstile.scriptFail": "Turnstile script failed to load",
    "turnstile.verifyFail": "Verification failed",
    "turnstile.componentFail": "Verification component failed to load",
    "error.routeTitle": "Route Error",
    "error.renderFail": "Render error",
    "spinner.loading": "Loading",
    "detail.mem": "Memory",
    "detail.disk": "Disk",
    "common.cores": "cores",
    "common.unconfigured": "Unconfigured",
    "overview.online": "Online Nodes",
    "overview.bandwidth": "Live Bandwidth",
    "overview.traffic": "Total Traffic",
    "overview.all": "All",
    "overview.empty.title": "No nodes connected yet",
    "overview.empty.sub": "Waiting for backend push, or add nodes in the admin panel",
    "overview.loadfail.title": "Node data temporarily unavailable",
    "overview.loadfail.sub": "Waiting for backend auto-retry",
    "traffic.date": "Date",
    "traffic.today": "Today's Traffic",
    "traffic.peak": "Today's Peak",
    "traffic.nodes": "Node Details",
    "traffic.peakNote": "Peaks estimated from history samples",
    "traffic.statTo": "as of",
    "traffic.chartTitle": "Node Traffic & Speed",
    "traffic.startDate": "Start Date",
    "traffic.waiting": "Waiting for samples",
    "traffic.estimate": "Left axis cumulative estimated by integration",
    "traffic.emptyRange": "No samples in this range",
    "traffic.needLogin": "Login required to view more than 1 day",
    "traffic.retention": "Only the last 14 days are retained",
    "traffic.chartFail": "Chart failed to load",
    "traffic.cumUp": "Cum. Up",
    "traffic.cumDown": "Cum. Down",
    "traffic.rateUp": "Up Rate",
    "traffic.rateDown": "Down Rate",
    "traffic.columnNode": "Node",
    "traffic.columnTotal": "Today",
    "traffic.columnPeakUp": "Peak Up",
    "traffic.columnPeakDown": "Peak Down",
    "traffic.columnAction": "Actions",
    "traffic.columnLive": "Live",
    "traffic.up": "Up",
    "traffic.down": "Down",
    "traffic.noPeak": "No peak",
    "detail.region": "Region",
    "detail.group": "Group",
    "detail.os": "OS",
    "detail.kernel": "Kernel",
    "detail.cpu": "CPU",
    "detail.arch": "Arch",
    "detail.gpu": "GPU",
    "detail.stack": "IPv4 / IPv6",
    "detail.agent": "Agent",
    "detail.uptime": "Uptime",
    "detail.load": "Load",
    "detail.conns": "Connections",
    "detail.proc": "Processes",
    "detail.notFound": "Instance not found. It may have been deleted or the link is invalid.",
    "detail.listFail": "Node list failed to load, retrying automatically.",
    "detail.loading": "Loading instance…",
    "chart.loadTitle": "Load Charts",
    "chart.pingTitle": "Ping Charts",
    "chart.spanGaps": "Connect Gaps",
    "chart.loadFail": "Load history failed to load",
    "chart.loadEmpty": "No load history yet",
    "chart.pingFail": "Latency history failed to load",
    "chart.pingEmpty": "No latency records",
    "chart.retrying": "Retrying",
    "chart.refreshing": "Refreshing",
    "chart.refreshFail": "Failed, retry",
    "chart.hideAll": "Hide All",
    "chart.showAll": "Show All",
    "chart.lossBand": "Loss Band",
    "chart.smooth": "Peak Smoothing",
    "chart.allHidden": "All lines hidden — use the buttons above to restore",
    "chart.coverage": "Coverage",
    "chart.sampling": "Sampling",
    "settings.defaultAppearance": "Default Appearance",
    "settings.cardView": "Card View",
    "settings.homeSort": "Home Sorting",
    "settings.defaultSort": "Default Sort",
    "settings.defaultDir": "Default Direction",
    "settings.cardLayout": "Card Layout",
    "settings.auto": "Auto",
    "settings.cols": "cols",
    "settings.groupOrder": "Group Order (drag to reorder)",
    "settings.noGroups": "No groups configured for nodes yet.",
    "settings.homeShow": "Home Display",
    "settings.showOverview": "Show Overview",
    "traffic.chartAria": "Node daily traffic & speed dual-axis chart",
    "range.h6": "6 Hours",
    "range.h12": "12 Hours",
    "range.d2": "2 Days",
    "settings.showOverviewDesc": "Online/offline/bandwidth summary panel",
    "settings.showGroupTabsDesc": "Switch by node group",
    "settings.showRegionBarDesc": "Aggregate by region",
    "settings.compactTraffic": "Compact: Show Total Traffic",
    "settings.compactUptime": "Compact: Show Uptime",
    "settings.showConnectionsDesc": "TCP/UDP (probe-reported)",
    "settings.multiPingDesc": "Show multi-line comparison on large/compact cards; single line when off",
    "settings.fakePingDesc": "Simulated latency for visitors, enabled by the admin",
    "settings.adminBtnDesc": "ADMIN button in the top bar",
    "settings.cardLayoutHint": "Auto adapts columns by card min-width; with a fixed count, large/compact/mini cards all follow it.",
    "settings.cardViewHint": "Desktop and mobile share the same view; LIST falls back to compact cards on mobile.",
    "manage.currentUsing": "This device is using:",
    "manage.saveLocalHint": "the new appearance is written after clicking Save Locally",
    "manage.resetHint": "Discard unsaved changes",
    "manage.restoreSiteHint": "Discard local settings, use backend config",
    "manage.copyJsonHint": "Export full config JSON, paste into admin theme custom config",
    "manage.saveSiteHint": "Write directly into backend theme_options for all visitors",
    "settings.showGroupTabs": "Show Group Tabs",
    "settings.showRegionBar": "Show Region Stats",
    "settings.showCardGroup": "Show Group on Cards",
    "settings.compactList": "Compact & List",
    "settings.showConnections": "Show Connections",
    "settings.listCols": "Table Columns (LIST view)",
    "settings.pingLines": "Latency Lines",
    "settings.multiPing": "Multi-line Mode",
    "settings.fakePing": "Fake Data for Unbound",
    "settings.defaultLine": "Default Line",
    "settings.other": "Other",
    "settings.adminBtn": "Show Admin Entry",
    "settings.pingChart": "Show Ping Chart on Detail",
    "settings.hiddenNodes": "Hidden nodes (one name or UUID per line)",
    "settings.surface": "Card Opacity",
    "appearance.light": "Light",
    "appearance.system": "System",
    "appearance.dark": "Dark",
    "view.large": "Large Cards",
    "view.compact": "Compact Cards",
    "view.mini": "Mini Cards",
    "view.list": "List",
    "view.desktop": "Desktop",
    "view.mobile": "Mobile",
    "sort.asc": "↑ Ascending",
    "sort.desc": "↓ Descending",
    "sort.default": "Default",
    "sort.name": "Name",
    "sort.speed": "Live Speed",
    "sort.traffic": "Total Traffic",
    "manage.reset": "Reset",
    "manage.restoreSite": "Use Site Config",
    "manage.copyJson": "Copy Config JSON",
    "manage.saveLocal": "Save Locally",
    "manage.saveSite": "Save to Site",
    "manage.saving": "Saving…",
    "manage.publishing": "Publishing…",
    "manage.saveLocalDone": "Theme settings saved to this browser",
    "manage.saveSiteDone": "Saved to backend — all devices and visitors will use this as default",
    "manage.restoreDone": "Local settings discarded, now using backend config",
    "manage.copyDone": "Config JSON copied — paste it into admin Appearance → Theme Custom Config",
    "manage.copyFail": "Copy failed, check clipboard permissions",
    "manage.loginExpired": "Session expired — log in again at /admin, then save to site (local settings unaffected)",
    "manage.turnstile": "This site requires human verification — complete the challenge, then save to site again",
    "manage.invalidFormat": "Config rejected by backend (invalidThemeOptionsFormat) — please report this to the author",
    "manage.saveFail": "Save failed",
    "manage.siteHint": "Logged-in admins can use Save to Site to write settings into theme_options for all visitors; otherwise copy the JSON into admin Appearance → Theme Custom Config.",
    "shell.accessError": "Failed to load site config",
    "shell.accessErrorSub": "Check the network and retry.",
    "shell.private": "Access Restricted",
    "shell.privateSub": "This site is private — log in to view node data.",
    "shell.gotoLogin": "Go to Login",
    "shell.more": "More",
    "shell.colors": "Card Colors",
    "shell.theme": "Theme",
    "lang.switch": "Switch Language",
    "shell.cardView": "Card View",
    "shell.refreshLoading": "Fetching 1-hour latency history for {n} nodes…",
    "shell.refreshBase": "Refresh latency data: fetch 1-hour real samples for {n} nodes",
    "shell.lastRefresh": "Last refresh",
    "turnstile.title": "Authentication",
    "turnstile.desc": "This site has Cloudflare Turnstile enabled — pass the check to view node data.",
    "turnstile.fail": "Verification failed, please retry",
    "turnstile.widgetFail": "Verification widget failed to load",
    "turnstile.expired": "Verification expired, please retry",
    "realtime.expired": "Live connection reached its time limit and disconnected",
    "realtime.limit": "Site limits a single live connection to",
    "realtime.paused": "Page is showing data from before the disconnect.",
    "realtime.continue": "Continue",
    "error.title": "Something went wrong",
    "error.hint": "Refresh the page, or go back to the home page.",
    "error.diag": "Diagnostics (screenshot or copy when reporting)",
    "error.copy": "Copy Diagnostics",
    "error.reload": "[ RELOAD ]",
    "error.routeFail": "Failed to load this route.",
    "notfound.title": "Page Not Found",
    "nav.assets": "Assets",
    "nav.traffic": "Traffic",
    "nav.settings": "Settings",
    "nav.admin": "Admin",
    "title.status": "System Status",
    "title.traffic": "Today's Traffic",
    "title.assets": "Asset Summary",
    "title.settings": "Theme Settings",
    "status.online": "ONLINE",
    "status.offline": "OFFLINE",
    "status.pending": "Waiting for backend…",
    "footer.tagline": "End of transmission // Glory to mankind",
  },
} as const;

export type I18nKey = keyof (typeof STRINGS)["zh"];

function readStoredLang(): Lang {
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    // 默认英文（自输入内容不翻译）；用户可切回中文。
    return raw === "zh" ? "zh" : "en";
  } catch {
    return "en";
  }
}

let lang: Lang = readStoredLang();
const listeners = new Set<() => void>();

function subscribe(listener: () => void) {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}

function getSnapshot() {
  return lang;
}

function emit() {
  for (const listener of listeners) listener();
}

/** 非组件场景（class 组件、模块级函数）用的翻译函数。 */
export function translate(key: I18nKey): string {
  return STRINGS[lang][key] ?? STRINGS.zh[key] ?? key;
}

export function setLang(next: Lang) {
  if (lang === next) return;
  lang = next;
  try {
    window.localStorage.setItem(STORAGE_KEY, next);
  } catch {
    // 隐私模式写不进去时，本次会话内仍生效。
  }
  emit();
}

export function getLang(): Lang {
  return lang;
}

/** 语言切换 + 翻译函数。默认 zh，用户可切到 en；持久化在 localStorage。 */
export function useLanguage() {
  const current = useSyncExternalStore(subscribe, getSnapshot, getSnapshot);
  const set = useCallback((next: Lang) => setLang(next), []);
  const t = useCallback(
    (key: I18nKey) => STRINGS[current][key] ?? STRINGS.zh[key] ?? key,
    [current],
  );
  return { lang: current, setLang: set, t };
}
